/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:130c52cf-8766-4ac4-8bc4-d89ed66a927d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_rAPBc8JHr",
    "aws_user_pools_web_client_id": "3av2tltssvu5u8mj7ee0jsj0b5",
    "oauth": {}
};


export default awsmobile;
